# Generated by Django 2.1.1 on 2018-10-29 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_missao', models.CharField(max_length=200)),
                ('xp_missao', models.FloatField()),
                ('data', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='jogador',
            old_name='xp',
            new_name='xp_total',
        ),
        migrations.AddField(
            model_name='jogador',
            name='m_adquiridas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='m_realizadas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='mr_nadata',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='private_token',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missao',
            name='jogador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Jogador', to='jogador.Jogador'),
        ),
    ]
