# Generated by Django 2.1.1 on 2018-10-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0004_auto_20181028_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missao',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
