# Generated by Django 2.1.1 on 2018-10-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0005_auto_20181029_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='url_imagem',
            field=models.TextField(default=''),
        ),
    ]
