# Generated by Django 2.1.1 on 2018-10-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0006_jogador_url_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='id_issue',
            field=models.IntegerField(default=0),
        ),
    ]
