# Generated by Django 2.1.1 on 2018-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0007_missao_id_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='url_imagem',
            field=models.CharField(default='', max_length=300),
        ),
    ]
