# Generated by Django 2.1.1 on 2018-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0009_auto_20181030_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='id_projeto',
            field=models.IntegerField(default=0),
        ),
    ]
